name: Build Latex document

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: aanda.tex
      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: aanda.pdf
      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aanda.pdf
          asset_name: aanda_$tag.pdf
          tag: ${{ github.ref }}
          overwrite: true
          body: "Automatic release through Github Actions"
